apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: prod
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      name: product-service
      labels:
        app: product-service
    spec:
#      nodeSelector:
#        nodegroup: cloud5
      containers:
        - name: product-service
          image: nowgnas/bb:product
          imagePullPolicy: Always
          ports:
            - containerPort: 8800
          resources:
            requests:
              memory: "512Mi"
              cpu: "400m"
          env:
            - name: USE_PROFILE
              value: "prod"
            - name: SPRING_CONFIG_ACTIVATE_ON_PROFILE
              value: "prod"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8800
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 2
          # 애플리케이션이 정상 상태를 유지하고 있는지 지속해서 검사
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8800
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 2
      restartPolicy: Always

